# Generated by Django 3.2.7 on 2021-11-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOfUser', models.IntegerField(default=1, max_length=1, verbose_name='사용자수')),
                ('groupID', models.CharField(max_length=8, unique=True, verbose_name='그룹번호')),
                ('OTTname', models.CharField(max_length=15, verbose_name='OTT이름')),
                ('isFull', models.BooleanField(default=False, verbose_name='풀방임?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='그룹생성시간')),
                ('user1code', models.CharField(max_length=50, unique=True, verbose_name='user1 코드')),
                ('user2code', models.CharField(max_length=50, null=True, unique=True, verbose_name='user2 코드')),
                ('user3code', models.CharField(max_length=50, null=True, unique=True, verbose_name='user3 코드')),
                ('user4code', models.CharField(max_length=50, null=True, unique=True, verbose_name='user4 코드')),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
