# Generated by Django 3.2.7 on 2021-11-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211121_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='numOfUser',
            field=models.IntegerField(default=1, verbose_name='사용자수'),
        ),
    ]
