# Generated by Django 3.2.7 on 2021-11-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_group_numofuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user1code',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user2code',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user3code',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user4code',
        ),
        migrations.AddField(
            model_name='group',
            name='user1ID',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='user1 아이디'),
        ),
        migrations.AddField(
            model_name='group',
            name='user2ID',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='user2 아이디'),
        ),
        migrations.AddField(
            model_name='group',
            name='user3ID',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='user3 아이디'),
        ),
        migrations.AddField(
            model_name='group',
            name='user4ID',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='user4 아이디'),
        ),
    ]
