# Generated by Django 3.2.7 on 2021-11-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_laftel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_netflix',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_tving',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_watcha',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_wavve',
        ),
        migrations.AlterField(
            model_name='user',
            name='OTTname',
            field=models.CharField(default='아직 OTT를 선택하지 않았습니다.', max_length=20, verbose_name='OTT 이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=100, unique=True, verbose_name='이메일 주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='사용자 별명'),
        ),
        migrations.AlterField(
            model_name='user',
            name='realname',
            field=models.CharField(default='', max_length=100, verbose_name='이름(실명)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(default='', max_length=100, verbose_name='ID'),
        ),
    ]
