# Generated by Django 3.1.4 on 2021-11-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20211124_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='OTTname',
            field=models.CharField(default='아직 OTT를 선택하지 않았습니다.', max_length=20, verbose_name='OTT'),
        ),
        migrations.AddField(
            model_name='user',
            name='groupID',
            field=models.CharField(default='아직 그룹에 참가하지 않았습니다.', max_length=20, verbose_name='그룹 아이디'),
        ),
        migrations.AddField(
            model_name='user',
            name='isAttend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_Login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_laftel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_netflix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_tving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_watcha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_wavve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='realName',
            field=models.CharField(default='', max_length=20, verbose_name='이름(실명)'),
        ),
        migrations.AddField(
            model_name='user',
            name='userCode',
            field=models.CharField(default='', max_length=20, verbose_name='유저 코드'),
        ),
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(default='', max_length=20, verbose_name='사용자 별명'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='이메일 주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='아이디'),
        ),
    ]
