# Generated by Django 3.2.7 on 2021-11-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20211124_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNum',
            field=models.CharField(default='휴대폰 번호를 입력해주세요. (- 제외)', max_length=11, verbose_name='휴대폰 번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='realName',
            field=models.CharField(default='이름을 입력해주세요.', max_length=20, verbose_name='이름(실명)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(default='별명을 입력해주세요', max_length=20, verbose_name='사용자 별명'),
        ),
    ]
